HolidayClub.Web/Models/ContactDetailsViewModel.cs
namespace HolidayClub.Web.Models
{
    using System.ComponentModel.DataAnnotations;

    using Enums;

    public class ContactDetailsViewModel
    {
        public string Title { get; set; }

        public string Forename { get; set; }

        [Required]
        public string Surname { get; set; }

        [Display(Name = "Relation to child")]
        public string RelationToChild { get; set; }

        public string Address { get; set; }

        public string Postcode { get; set; }

        [Display(Name = "Telephone number(s)")]
        public string TelephoneNumber1 { get; set; }
        public string TelephoneNumber2 { get; set; }
        public string TelephoneNumber3 { get; set; }

        [Display(Name = "Email address")]
        [Required]
        public string Email { get; set; }

        [Display(Name = "Correspondence preference")]
        [Required]
        public CorrespondencePreference CorrespondencePreference { get; set; }

        [Display(Name = "Single parent?")]
        public SingleParentStatus SingleParentStatus { get; set; }

        [Display(Name = "Keep me informed?")]
        [Required]
        public bool IsToBeKeptInformed { get; set; }
    }
}

HolidayClub.Web/Models/ErrorViewModel.cs
using System;

namespace HolidayClub.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HolidayClub.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HolidayClub.Web.Models;

namespace HolidayClub.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HolidayClub.Web/Controllers/ParentController.cs
namespace HolidayClub.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Security.Claims;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Data;
    using Enums;
    using Models;

    [Authorize]
    public class ParentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ParentController (ApplicationDbContext context)
        {
            _context = context;
        }

        public ViewResult ContactDetails()
        {
            var contactDetails = GetContactDetails();

            var viewModel = new ContactDetailsViewModel
            {
                Title = contactDetails.Title,
                Forename = contactDetails.Forename,
                Surname = contactDetails.Surname,
                RelationToChild = contactDetails.RelationToChild,
                Address = contactDetails.Address,
                Postcode = contactDetails.Postcode,
                TelephoneNumber1 = contactDetails.TelephoneNumber1,
                TelephoneNumber2 = contactDetails.TelephoneNumber2,
                TelephoneNumber3 = contactDetails.TelephoneNumber3,
                Email = contactDetails.Email,
                IsToBeKeptInformed = contactDetails.IsToBeKeptInformed
            };


            if (contactDetails.IsSingleParent == true)
                viewModel.SingleParentStatus = SingleParentStatus.Yes;
            else if (contactDetails.IsSingleParent == false)
                viewModel.SingleParentStatus = SingleParentStatus.No;
            else
                viewModel.SingleParentStatus = SingleParentStatus.NotSpecified;


            if (contactDetails.CorrespondencePreference == null)
                viewModel.CorrespondencePreference = CorrespondencePreference.NoCorrespondence;
            else
                viewModel.CorrespondencePreference = Enum.Parse<CorrespondencePreference>(contactDetails.CorrespondencePreference);


            return View(viewModel);
        }
        [HttpPost]
        public ViewResult ContactDetails(ContactDetailsViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var contactDetails = GetContactDetails();

            contactDetails.Title = viewModel.Title;
            contactDetails.Forename = viewModel.Forename;
            contactDetails.Surname = viewModel.Surname;
            contactDetails.RelationToChild = viewModel.RelationToChild;
            contactDetails.Address = viewModel.Address;
            contactDetails.Postcode = viewModel.Postcode;
            contactDetails.TelephoneNumber1 = viewModel.TelephoneNumber1;
            contactDetails.TelephoneNumber2 = viewModel.TelephoneNumber2;
            contactDetails.TelephoneNumber3 = viewModel.TelephoneNumber3;
            contactDetails.Email = viewModel.Email;
            contactDetails.CorrespondencePreference = viewModel.CorrespondencePreference.ToString();
            contactDetails.IsToBeKeptInformed = contactDetails.IsToBeKeptInformed;

            if (viewModel.SingleParentStatus != SingleParentStatus.NotSpecified)
            {
                contactDetails.IsSingleParent = viewModel.SingleParentStatus == SingleParentStatus.Yes;
            }

            _context.SaveChanges();

            return View(viewModel);
        }

        private ContactDetails GetContactDetails()
        {
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var contactDetails =
                _context.ContailDetails
                    .FirstOrDefault(c =>
                        c.AspNetUserId == currentUserId
                    );

            if (contactDetails == null)
            {
                contactDetails = new ContactDetails
                {
                    AspNetUserId = currentUserId
                };
                _context.ContailDetails.Add(contactDetails);
                _context.SaveChanges();
            }

            return contactDetails;
        }
    }
}

HolidayClub.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HolidayClub.Web/Views/Parent/ContactDetails.cshtml
@using HolidayClub.Web.Enums;

@model HolidayClub.Web.Models.ContactDetailsViewModel

@{
    ViewData["Title"] = "ContactDetails";
}

<div id="contact-details-page">
    <h1>Contact Details</h1>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="ContactDetails">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Forename" class="control-label"></label>
                    <input asp-for="Forename" class="form-control" />
                    <span asp-validation-for="Forename" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Surname" class="control-label"></label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RelationToChild" class="control-label"></label>
                    <input asp-for="RelationToChild" class="form-control" />
                    <span asp-validation-for="RelationToChild" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <textarea asp-for="Address" class="form-control"></textarea>
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Postcode" class="control-label"></label>
                    <input asp-for="Postcode" class="form-control" />
                    <span asp-validation-for="Postcode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TelephoneNumber1" class="control-label"></label>
                    <input asp-for="TelephoneNumber1" class="form-control" />
                    <span asp-validation-for="TelephoneNumber1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="TelephoneNumber2" class="form-control" />
                    <span asp-validation-for="TelephoneNumber2" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="TelephoneNumber3" class="form-control" />
                    <span asp-validation-for="TelephoneNumber3" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CorrespondencePreference" class="control-label"></label>
                    <select asp-for="CorrespondencePreference" asp-items="Html.GetEnumSelectList<CorrespondencePreference>()" class="form-control"></select>
                    <span asp-validation-for="CorrespondencePreference" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SingleParentStatus" class="control-label"></label>
                    <select asp-for="SingleParentStatus" asp-items="Html.GetEnumSelectList<SingleParentStatus>()" class="form-control"></select>
                    <span asp-validation-for="SingleParentStatus" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IsToBeKeptInformed" class="control-label"></label>
                    <div>
                        <input type="checkbox" asp-for="IsToBeKeptInformed" />
                    </div>
                    <span asp-validation-for="IsToBeKeptInformed" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        Save
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HolidayClub.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HolidayClub.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HolidayClub.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parent" asp-action="ContactDetails">Contact Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HolidayClub.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>